In [1]:
import pandas as pd
import matplotlib .pyplot as plt

In [2]:
df_path = f"Resources/covid-data.csv"
df_who=pd.read_csv(df_path)

df_who.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-02-24,AF,Afghanistan,EMRO,1,1,0,0
1,2020-02-25,AF,Afghanistan,EMRO,0,1,0,0
2,2020-02-26,AF,Afghanistan,EMRO,0,1,0,0
3,2020-02-27,AF,Afghanistan,EMRO,0,1,0,0
4,2020-02-28,AF,Afghanistan,EMRO,0,1,0,0

In [3]:
#1. which WHO region has the most cumulative case as of now?
#2. top 5 countries has the most cumulative case as of now?
#3. which country managed to reduce their daily case peak?
#4. which countries is experiencing its daily virus case peak?

In [11]:
df_who.columns = df_who.columns.str.replace(' ','')
df_who.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-02-24,AF,Afghanistan,EMRO,1,1,0,0
1,2020-02-25,AF,Afghanistan,EMRO,0,1,0,0
2,2020-02-26,AF,Afghanistan,EMRO,0,1,0,0
3,2020-02-27,AF,Afghanistan,EMRO,0,1,0,0
4,2020-02-28,AF,Afghanistan,EMRO,0,1,0,0

In [ ]:
#1